# Generated by Django 3.1.3 on 2020-12-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cit2020', '0002_auto_20201204_1936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='level',
            new_name='question',
        ),
        migrations.RenameModel(
            old_name='total_level',
            new_name='total_question',
        ),
        migrations.RenameField(
            model_name='total_question',
            old_name='totallevel',
            new_name='totalquestion',
        ),
    ]
