# Generated by Django 3.1.3 on 2020-12-04 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cit2020', '0004_auto_20201204_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='save_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=200)),
                ('q_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cit2020.question')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
