# Generated by Django 3.1.3 on 2020-12-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cit2020', '0006_auto_20201204_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save_answer',
            old_name='q_no',
            new_name='question',
        ),
    ]
