# Generated by Django 3.1.3 on 2020-12-04 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cit2020', '0007_auto_20201204_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cit2020.question'),
        ),
        migrations.AlterField(
            model_name='save_answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
