# Generated by Django 3.1.3 on 2020-12-05 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cit2020', '0008_auto_20201204_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save_answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='save_answer',
            name='user',
        ),
        migrations.DeleteModel(
            name='total_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='audio',
        ),
        migrations.DeleteModel(
            name='save_answer',
        ),
    ]
