# Generated by Django 3.1.3 on 2020-12-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit2020', '0009_auto_20201206_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
