# Generated by Django 3.1.3 on 2020-12-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit2020', '0010_auto_20201206_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
