# Generated by Django 3.2.9 on 2022-01-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit2020', '0016_auto_20220101_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='slotTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot1start', models.DateTimeField()),
                ('slot1end', models.DateTimeField()),
                ('slot2start', models.DateTimeField()),
                ('slot2end', models.DateTimeField()),
                ('slot3start', models.DateTimeField()),
                ('slot3end', models.DateTimeField()),
            ],
        ),
    ]
