# Generated by Django 3.2.9 on 2022-01-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit2020', '0018_auto_20220102_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slottime',
            name='slot1start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
