# Generated by Django 3.2.9 on 2022-01-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit2020', '0020_alter_slottime_slot1start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slottime',
            name='slot1end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='slottime',
            name='slot1start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='slottime',
            name='slot2end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='slottime',
            name='slot2start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='slottime',
            name='slot3end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='slottime',
            name='slot3start',
            field=models.DateTimeField(),
        ),
    ]
