# Generated by Django 3.2.9 on 2022-01-02 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cit2020', '0021_auto_20220102_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slottime',
            old_name='slot1end',
            new_name='slotend',
        ),
        migrations.RenameField(
            model_name='slottime',
            old_name='slot1start',
            new_name='slotstart',
        ),
        migrations.RemoveField(
            model_name='slottime',
            name='slot2end',
        ),
        migrations.RemoveField(
            model_name='slottime',
            name='slot2start',
        ),
        migrations.RemoveField(
            model_name='slottime',
            name='slot3end',
        ),
        migrations.RemoveField(
            model_name='slottime',
            name='slot3start',
        ),
    ]
