# Generated by Django 3.2.9 on 2022-01-02 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cit2020', '0022_auto_20220102_0926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slotTime',
        ),
    ]
