# Generated by Django 3.2.9 on 2022-01-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit2020', '0023_delete_slottime'),
    ]

    operations = [
        migrations.CreateModel(
            name='slotTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot1start', models.CharField(max_length=200, null=True)),
                ('slot1end', models.CharField(max_length=200, null=True)),
                ('slot2start', models.CharField(max_length=200, null=True)),
                ('slot2end', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
