# Generated by Django 3.2.9 on 2022-01-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit2020', '0024_slottime'),
    ]

    operations = [
        migrations.AddField(
            model_name='slottime',
            name='slot3end',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slottime',
            name='slot3start',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
