# Generated by Django 3.2.9 on 2022-01-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit2020', '0026_auto_20220102_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slottime',
            name='slot1end',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slottime',
            name='slot1start',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slottime',
            name='slot2end',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slottime',
            name='slot2start',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slottime',
            name='slot3end',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slottime',
            name='slot3start',
            field=models.IntegerField(default=0),
        ),
    ]
