# Generated by Django 3.2.9 on 2022-01-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cit2020', '0027_auto_20220102_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slotTime',
        ),
    ]
