# Generated by Django 3.2.9 on 2022-01-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cit2020', '0028_delete_slottime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot2',
            name='user',
        ),
        migrations.RemoveField(
            model_name='slot3',
            name='user',
        ),
        migrations.DeleteModel(
            name='Slot1',
        ),
        migrations.DeleteModel(
            name='Slot2',
        ),
        migrations.DeleteModel(
            name='Slot3',
        ),
    ]
