# Generated by Django 3.2.9 on 2022-01-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit2020', '0029_auto_20220102_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='qualified',
            field=models.BooleanField(default=False),
        ),
    ]
